### ISSUE TITLE
#3

### ISSUE THREAD

**Issue by alirezac0** [MohammadSh79/SE140102Group6#8]
## The update includes the following page:
- Profile page

_each page has a Dark & a Light mode_

**Comment by MohammadSh79** [comment]
```
هر شخص پس از پایان  issueمورد نظر، در این صفحه پس از ذکر شماره issue
(به شکل  #100 برای مثال)، توضیح مختصری از فعالیت انجام گرفته اضافه میکند. 
```

صفحه پروفایل برای Sprint 1 هست.
صفحه ویرایش پروفایل و اعلانها به ترتیب برای اسپرینت 2 و 3 هستند و باید تو پوشه مربوط به خودشون قرار بگیرن. برای هرکدوم هم باید Issue با شماره مربوط به خودش رو ایجاد کنی. درحال حاضر هم روی اسپرینت 2 هستیم و به 3 نرسیدیم.
